### ISSUE TITLE
How to transfer back the resolved response data to the store- mode proxy ?

### ISSUE THREAD

**Issue by SamuraizSupport** [adobe/frl-online-proxy#28]
In our scenario,  two instances of FRL Online Proxy, one for store mode  and the other for forward mode, are running on different networks. 

Now,  user guide as follows explains:
https://opensource.adobe.com/frl-online-proxy/en/#cache-management
"Store and Forward
In this case, resolved response data will need to be manually transferred back to the machine on the isolated network and imported into the “store mode” proxy instance’s database."

Though, there is no information how to do this. Please let me know how to transfer back the resolved response data on the proxy of forward mode to the proxy of store mode.  

Thank you

**Comment by adobeDan** [comment]
Hi @SamuraizSupport, thanks for the question.  I'll state the procedure here than we will get it added to the docs.

1. Let's call the instances SI and FI (Storing Instance and Forwarding Instance).  Let's say SI and FI both are configured to use databases that are called `proxy-db.sqlite`.
2. Stop the SI instance for a moment.  Collect all the unanswered requests it has accumulated by invoking `frl-proxy export stored-requests.sqlite`.  (This exports any unanswered requests in `proxy-db.sqlite` to a new database `stored-requests.sqlite`.). Then restart the SI instance.
3. Move the `stored-requests.sqlite` database file to the FI instance location and rename it `frl-proxy.sqlite` so it's the database used by FI.
4. Forward all the stored requests by, on FI, invoking `frl-proxy -m forward`.  This will complete quickly, sending all the stored requests in the `frl-proxy.sqlite` database to the server and keeping the responses in the same database.
5. Move the `frl-proxy.sqlite` database to the SI instance location and rename it `forwarded-requests.sqlite`.
6. Stop the SI instance for a moment.  Import the database of forwarded responses into the SI instance by invoking `frl-proxy import forwarded-requests.sqlite`.  This will move all the requests into the `proxy-db.sqlite` file.  Restart the SI instance.

At this point all the forwarded request responses will be available to the storing instance, so any apps whose requests had been stored will be successfully activated when they are next launched.

Please let us know if these instructions are clear, and you can get things working.  When you are successful, we will update the docs.

**Comment by SamuraizSupport** [comment]
Hi
Thank you very much for your reply. 
Let me confirm :
> Stop the SI instance for a moment. Import the database of forwarded responses into the SI instance by invoking frl-proxy import forwarded-requests.sqlite. This will move all the requests into the proxy-db.sqlite file. Restart the SI instance.

According to the user guide, import option described as follows:
> import is used with a proxy that will run in forward mode to fulfill a batch of unfulfilled license requests. It imports request data from a database file that was generated using export.

So you are suggesting  the import option is valid on instance run in stored mode. Let me know if I misunderstand. 

Thank you,

**Comment by adobeDan** [comment]
Yes, the current docs are wrong.  Both export and import are used on the "Stored Instance".  All you do with the "Forwarding Instance" is use the *export* db from the SI *as the proxy db* when you run the forwarder.  It then caches all the responses in that same db, and then you take that db back to the SI instance and *import* it.  Hope this helps clarify things.  Please give it a try.

**Comment by SamuraizSupport** [comment]
OK thanks!  I will give it a try.

**Comment by adobeDan** [comment]
@SamuraizSupport can you confirm this process worked for you?  If so, I'll add it to the docs.
