### ISSUE TITLE
Service.ps1 Fails to Properly Install Windows Service

### ISSUE THREAD

**Issue by mikeinsf** [adobe/frl-online-proxy#30]
**Description**
Configuration file improperly defined in service.ps1
Variable $cfg defined with full path. Service fails to start, goes into Paused state.
Redefined variable simply as "proxy-conf.toml" to properly install the service.

**Steps to reproduce**
* Powershell prompt as Administrator, run "service.ps1 start"

**Expected behavior**
FRL Proxy service should succeed and enter a Running state.

**Environment**
 - frl-proxy version: 1.0.1
 - OS type and version: Windows Server 2019

**Comment by adobeDan** [comment]
@adorton-adobe Can you take a look at this one?  You are more familiar with the Windows Service stuff than I am.

**Comment by adobeDan** [comment]
@mikeinsf Thanks for the bug report.  I'm trying to reproduce it I have a question for you.

As I understand things, the `service.ps1` script expects to be located in the same directory as the `frl-proxy.exe` executable file, and it also expects the config file to be in that same directory.  Are you running with a different configuration? (I'm guessing that you are invoking the script while in a different directory than the proxy executable, and you are trying to specify a config file that's in the same directory from which you're invoking the script.  Is that correct?)

**Comment by maartenpols-united** [comment]
I have the same issue, powershell is running in administrator mode, frl-proxy.exe and proxy-conf.toml are in the same folder as service.ps1. frl-proxy.exe is running fine manual, however in servicemode it wont start.

**Comment by adobeDan** [comment]
@maartenpols-united Can you share logs of the service.ps1 run or the service failing to start?  Feel free to send them to my private email (available in my GitHub profile).

**Comment by maartenpols-united** [comment]
@adobeDan what do you mean with service.ps1 logs? the powershell script is not logging anything,
the console output is this:
_PS C:\Program Files\frl-proxy-win-1.1.0> .\service.ps1 start
Service "FRL Online Proxy" installed successfully!
FRL Online Proxy: Unexpected status SERVICE_PAUSED in response to START control._

if you try to start the service manual you get the error:
_Windows could not start the FRL Online Proxy service on local computer.
The service did not return an error. This could be an internal Windows error or an internal service error._

no new lines in the local proxy-log.log file, are there other log files to look at?

**Comment by adobeDan** [comment]
Hi @maartenpols-united, the likely cause of your problem is that you have configured your proxy so that it doesn't log to a file but instead tries to log to standard output.  `service.ps1` uses nssm to run the proxy as a service, and nssm doesn't allow programs to use standard output (unless it was told to redirect that to a file).  So please try the following:

1. remove the proxy with `service.ps1 remove`
2. run `frl-proxy configure`
2. when asked, say you want to configure logging.
3. use the option of logging to a file and specify the filename you want to use (default `frl-proxy.log`).
4. reinstall the proxy with `service.ps1 start`

Let me know if that produces better results, thanks!

**Comment by maartenpols-united** [comment]
@adobeDan 
The logging is already set to file, see my config file:
[proxy]
mode = "passthrough"
host = "0.0.0.0"
port = "8080"
ssl_port = "8443"
remote_host = "https://lcs-cops.adobe.io"
ssl = true

[ssl]
cert_path = "*******"
cert_password = "*******"

[logging]
level = "info"
destination = "file"
file_path = "frl-proxy-log.log"

[cache]
db_path = "proxy-cache.sqlite"

[network]
use_proxy = false
proxy_host = "127.0.0.1"
proxy_port = "8888"
use_basic_auth = false
proxy_username = ""
proxy_password = ""

**Comment by maartenpols-united** [comment]
@adobeDan i found the couse of the problem, with this command you can save the nssm output to a file:
nssm set [SERVICE_NAME] AppStdout [APP_PATH_INSTALL]\logs\service.log
nssm set [SERVICE_NAME] AppStderr [APP_PATH_INSTALL]\logs\service-error.log

and in the service-error.log i found this:
error: Found argument 'Files\frl-proxy-win-1.1.0\proxy-conf.toml'' which wasn't expected, or isn't valid in this context

my location of the files is: C:\Program Files\frl-proxy-win-1.1.0
I had to update your PS script:
./bin/nssm install $serviceName "$PSScriptRoot\frl-proxy.exe" "--config-file `"`"$cfg`"`" start";

now its working

**Comment by adobeDan** [comment]
Thanks @maartenpols-united for the debugging!  We will fix the script both to save nssm logs and to use quoting on arguments appropriately and republish it ASAP.
