### ISSUE TITLE
Healthmonitor

### ISSUE THREAD

**Issue by maartenpols-united** [adobe/frl-online-proxy#41]
Dear Developer,
I created a dockercontainer with FRL online proxy server, however can we add a healthpage to see if the service is healthy?
now if you go to https://localhost:8443 you get a 400 error page.

**Comment by adorton-adobe** [comment]
The proxy doesn't serve any pages on root. If you're using the latest version, then the `/status` endpoint will tell you that the proxy is running.

**Comment by maartenpols-united** [comment]
The status page is enough for the health monitor, I didn’t know there was a status page.

Met vriendelijke groet,
[logo EMG]
Maarten Pols
Support IT/AV Engineer
T
+31 (0)35-7733374

***@***.***
nl.emglive.com
Het Muziekpaviljoen (gebouw 1) | Frits Spitsstraat 3 | 1217 WC Hilversum | Nederland

[EMG: NEW NAME, SAME PEOPLE]

See nl.emglive.com/algemene-voorwaarden for review and downloading of our General Conditions. For our privacy statement please review nl.emglive.com/privacy-verklaring-emgnederlandbv.

**Comment by adorton-adobe** [comment]
No problem, thank you for reaching out.
