### ISSUE TITLE
cache-control CLI tweaks

### ISSUE THREAD

**Issue by adorton-adobe** [adobe/frl-online-proxy#7]
CLI options for `cache-control` need some tweaks -

* `--clear` is misidentified as an option in the usage text when it should be in the "flags" section. I believe this is because in the Opts struct it is defined as `Option<bool>`. Making it a plain bool with a default of `false` should resolve the issue. We won't run into the same issues we did with `--ssl` because there is nothing in the config that this option overrides.
* We should add an option to specify the path of the DB file to maintain consistency with the update I proposed in #5.
* We should add docstrings to `--export-file` and `--import-file` noting that these options are not yet implemented

**Comment by adorton-adobe** [comment]
The strongest reason to leave this as-is is that it sort of provides an extra layer of confirmation for performing a dangerous action. However, I think it may make more sense to follow the typical pattern of prompting the user for confirmation and perhaps even accepting a `-y` option to bypass that confirmation prompt.

```
$ ./frl-proxy cache-control --clear
Are you sure you want to clear the cache? This operation cannot be undone [yN]: Y
cache-control: Cache has been cleared
```

```
$ ./frl-proxy cache-control --clear -y
cache-control: Cache has been cleared
```

**Comment by adobeDan** [comment]
Great proposal!  I completely agree with your reasoning, @adorton-adobe.
