### ISSUE TITLE
Cache file created for operations that require existing cache

### ISSUE THREAD

**Issue by adorton-adobe** [adobe/frl-online-proxy#9]
**Description**

Certain operations don't make sense when the application isn't pointed to an existing, valid cache file.

* `cache-control --clear`
* `cache-control --export-file <file>`
* `start --mode forward`

Right now, the cache file is opened in read/write mode, which appears to create a new file at the specified path if it doesn't exist. For the aforementioned operations, this might create confusion for a user that has mistyped the filename and expects the operation to be performed on an existing cache file.

**Steps to reproduce**
* Run any of the aforementioned operations (e.g. `cache-control --clear`) with `cache.cache_file_path` set to a non-existent file.
* A new cache file will exist at the specified path

**Expected behavior**

* If clearing cache, exporting a cache file, or running in forward mode, check if the cache file exists. If it doesn't then report an error.
* If importing cache or running in cache or store mode, create the cache file if it doesn't exist and write a log message that the cache file has been created

**Comment by adobeDan** [comment]
I agree we should fix this for 0.9 release.  It's actually a good first issue, so marking it as such.

**Comment by adobeDan** [comment]
I realize I disagree about not creating the cache on --clear.  It's actually the call you would make to force the cache to be created so you could validate your initial configuration.
